declare @id as int

insert into [cms_agents].[CertStoreTypeProperties]([StoreTypeId], [Name], [DisplayName], [Type], [Required])
values
	(@id, 'access_token', 'Access Token', 3, 1),
	(@id, 'client_token', 'Client Token', 3, 1),
	(@id, 'client_secret', 'Client Secret', 3, 1),
	(@id, 'admin.addressLineOne', 'Admin - Address Line 1', 0, 1),
	(@id, 'admin.addressLineTwo', 'Admin - Address Line 2', 0, 1),
	(@id, 'admin.city', 'Admin - City', 0, 1), 
	(@id, 'admin.country', 'Admin - Country', 0, 1),
	(@id, 'admin.email', 'Admin - Email', 0, 1),
	(@id, 'admin.firstName', 'Admin - First Name', 0, 1),
	(@id, 'admin.lastName', 'Admin - Last Name', 0, 1),
	(@id, 'admin.organizationName', 'Admin - Organization Name', 0, 1),
	(@id, 'admin.phone', 'Admin - Phone', 0, 1),
	(@id, 'admin.postalCode', 'Admin - Postal Code', 0, 1),
	(@id, 'admin.region', 'Admin - Region', 0, 1),
	(@id, 'admin.title', 'Admin - Title', 0, 1),
	(@id, 'org.addressLineOne', 'Org - Address Line 1', 0, 1),
	(@id, 'org.addressLineTwo', 'Org - Address Line 2', 0, 1),
	(@id, 'org.city', 'Org - City', 0, 1), 
	(@id, 'org.country', 'Org - Country', 0, 1),
	(@id, 'org.organizationName', 'Org - Organization Name', 0, 1),
	(@id, 'org.phone', 'Org - Phone', 0, 1),
	(@id, 'org.postalCode', 'Org - Postal Code', 0, 1),
	(@id, 'org.region', 'Org - Region', 0, 1),
	(@id, 'tech.addressLineOne', 'Tech - Address Line 1', 0, 1),
	(@id, 'tech.addressLineTwo', 'Tech - Address Line 2', 0, 1),
	(@id, 'tech.city', 'Tech - City', 0, 1), 
	(@id, 'tech.country', 'Tech - Country', 0, 1),
	(@id, 'tech.email', 'Tech - Email', 0, 1),
	(@id, 'tech.firstName', 'Tech - First Name', 0, 1),
	(@id, 'tech.lastName', 'Tech - Last Name', 0, 1),
	(@id, 'tech.organizationName', 'Tech - Organization Name', 0, 1),
	(@id, 'tech.phone', 'Tech - Phone', 0, 1),
	(@id, 'tech.postalCode', 'Tech - Postal Code', 0, 1),
	(@id, 'tech.region', 'Tech - Region', 0, 1),
	(@id, 'tech.title', 'Tech - Title', 0, 1)
