# Creates all 1 store types via the Keyfactor Command REST API
# using PowerShell Invoke-RestMethod.
#
# Authentication (first matching method is used):
#   OAuth access token:   KEYFACTOR_AUTH_ACCESS_TOKEN
#   OAuth client creds:   KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET
#                         + KEYFACTOR_AUTH_TOKEN_URL
#   Basic auth (AD):      KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN
#
# Always required:
#   KEYFACTOR_HOSTNAME    Command hostname (e.g. my-command.example.com)
#
# Auto-generated by doctool generate-store-type-scripts — do not edit by hand.

if (-not $env:KEYFACTOR_HOSTNAME) {
    Write-Error "KEYFACTOR_HOSTNAME is required"
    exit 1
}

$uri     = "https://$($env:KEYFACTOR_HOSTNAME)/keyfactorapi/certificatestoretypes"
$headers = @{
    'Content-Type'               = "application/json"
    'x-keyfactor-requested-with' = "APIClient"
}

# ---------------------------------------------------------------------------
# Resolve auth
# ---------------------------------------------------------------------------
if ($env:KEYFACTOR_AUTH_ACCESS_TOKEN) {
    $headers['Authorization'] = "Bearer $($env:KEYFACTOR_AUTH_ACCESS_TOKEN)"
} elseif ($env:KEYFACTOR_AUTH_CLIENT_ID -and $env:KEYFACTOR_AUTH_CLIENT_SECRET -and $env:KEYFACTOR_AUTH_TOKEN_URL) {
    Write-Host "Fetching OAuth token..."
    $tokenBody = @{
        grant_type    = 'client_credentials'
        client_id     = $env:KEYFACTOR_AUTH_CLIENT_ID
        client_secret = $env:KEYFACTOR_AUTH_CLIENT_SECRET
    }
    $tokenResp = Invoke-RestMethod -Method Post -Uri $env:KEYFACTOR_AUTH_TOKEN_URL -Body $tokenBody
    $headers['Authorization'] = "Bearer $($tokenResp.access_token)"
} elseif ($env:KEYFACTOR_USERNAME -and $env:KEYFACTOR_PASSWORD -and $env:KEYFACTOR_DOMAIN) {
    $cred = [System.Convert]::ToBase64String(
        [System.Text.Encoding]::ASCII.GetBytes(
            "$($env:KEYFACTOR_USERNAME)@$($env:KEYFACTOR_DOMAIN):$($env:KEYFACTOR_PASSWORD)"))
    $headers['Authorization'] = "Basic $cred"
} else {
    Write-Error ("Authentication required. Set one of:`n" +
        "  KEYFACTOR_AUTH_ACCESS_TOKEN`n" +
        "  KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET + KEYFACTOR_AUTH_TOKEN_URL`n" +
        "  KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN")
    exit 1
}

function New-StoreType {
    param([string]$Name, [string]$Body)
    Write-Host "Creating $Name store type..."
    try {
        Invoke-RestMethod -Method Post -Uri $uri -Headers $headers -Body $Body -ContentType "application/json" | Out-Null
        Write-Host "  OK"
    } catch {
        Write-Warning "  FAILED: $($_.Exception.Message)"
    }
}

# ---------------------------------------------------------------------------
# Akamai — The Client Machine field is the Akamai REST API URL. This should be equal to the "host" value from the API credentials file.
# ---------------------------------------------------------------------------
New-StoreType "Akamai" @'
{
  "Name": "Akamai Certificate Provisioning Service",
  "ShortName": "Akamai",
  "Capability": "Akamai",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": false,
    "Create": false,
    "Discovery": false,
    "Enrollment": true,
    "Remove": false
  },
  "Properties": [
    {
      "Name": "access_token",
      "DisplayName": "Access Token",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": false
    },
    {
      "Name": "client_token",
      "DisplayName": "Client Token",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": false
    },
    {
      "Name": "client_secret",
      "DisplayName": "Client Secret",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": false
    }
  ],
  "EntryParameters": [
    {
      "Name": "EnrollmentId",
      "DisplayName": "Enrollment ID",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "Description": "Enrollment ID of a certificate enrollment in Akamai. This should only be supplied for ODKG when replacing an existing certificate."
    },
    {
      "Name": "ContractId",
      "DisplayName": "Contract ID",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "The Contract ID of your account in Akamai."
    },
    {
      "Name": "Sans",
      "DisplayName": "SANs",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "Description": "SANs for the new certificate. If multiple are supplied, they should be split with an ampersand character '&'"
    },
    {
      "Name": "admin-addressLineOne",
      "DisplayName": "Admin - Address Line 1",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-addressLineTwo",
      "DisplayName": "Admin - Address Line 2",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "Description": "Optional field for Administrator contact."
    },
    {
      "Name": "admin-city",
      "DisplayName": "Admin - City",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-country",
      "DisplayName": "Admin - Country",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-email",
      "DisplayName": "Admin - Email",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-firstName",
      "DisplayName": "Admin - First Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-lastName",
      "DisplayName": "Admin - Last Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-organizationName",
      "DisplayName": "Admin - Organization Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-phone",
      "DisplayName": "Admin - Phone",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-postalCode",
      "DisplayName": "Admin - Postal Code",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-region",
      "DisplayName": "Admin - Region",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-title",
      "DisplayName": "Admin - Title",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "org-addressLineOne",
      "DisplayName": "Org - Address Line 1",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Organization contact."
    },
    {
      "Name": "org-addressLineTwo",
      "DisplayName": "Org - Address Line 2",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "Description": "Optional field for Organization contact."
    },
    {
      "Name": "org-city",
      "DisplayName": "Org - City",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Organization contact."
    },
    {
      "Name": "org-country",
      "DisplayName": "Org - Country",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Organization contact."
    },
    {
      "Name": "org-organizationName",
      "DisplayName": "Org - Organization Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Organization contact."
    },
    {
      "Name": "org-phone",
      "DisplayName": "Org - Phone",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Organization contact."
    },
    {
      "Name": "org-postalCode",
      "DisplayName": "Org - Postal Code",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Organization contact."
    },
    {
      "Name": "org-region",
      "DisplayName": "Org - Region",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Organization contact."
    },
    {
      "Name": "tech-addressLineOne",
      "DisplayName": "Tech - Address Line 1",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "tech-addressLineTwo",
      "DisplayName": "Tech - Address Line 2",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "Description": "Optional field for Akamai Tech contact."
    },
    {
      "Name": "tech-city",
      "DisplayName": "Tech - City",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "tech-country",
      "DisplayName": "Tech - Country",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "tech-email",
      "DisplayName": "Tech - Email",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact. Must be an akamai.com email address."
    },
    {
      "Name": "tech-firstName",
      "DisplayName": "Tech - First Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "tech-lastName",
      "DisplayName": "Tech - Last Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "tech-organizationName",
      "DisplayName": "Tech - Organization Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "Akamai",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "tech-phone",
      "DisplayName": "Tech - Phone",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "tech-postalCode",
      "DisplayName": "Tech - Postal Code",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "tech-region",
      "DisplayName": "Tech - Region",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "tech-title",
      "DisplayName": "Tech - Title",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "deployment-network",
      "DisplayName": "Deployment Network",
      "Type": "MultipleChoice",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "Options": "Standard TLS,Enhanced TLS",
      "DefaultValue": "Standard TLS",
      "Description": "Required field for Deployment Network."
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathType": "MultipleChoice",
  "StorePathValue": "[\"Production\",\"Staging\"]",
  "PrivateKeyAllowed": "Forbidden",
  "ServerRequired": false,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Forbidden",
  "StorePathDescription": "The Akamai network the certificate will be managed from. Value can be either \"Production\" or \"Staging\"."
}
'@


Write-Host "Completed."
