# Store Type creation script using Invoke-RestMethod
# Generated by Doctool

# Configuration - set these variables before running
$KeyfactorHostname = $env:KEYFACTOR_HOSTNAME
$KeyfactorApiPath = if ($env:KEYFACTOR_API_PATH) { $env:KEYFACTOR_API_PATH } else { "KeyfactorAPI" }
$KeyfactorAuthToken = $env:KEYFACTOR_AUTH_TOKEN

$Headers = @{
    "Authorization" = "Bearer $KeyfactorAuthToken"
    "Content-Type" = "application/json"
    "x-keyfactor-requested-with" = "APIClient"
}

Write-Host "Creating store type: Akamai"
$Body = @'
{
  "Name": "Akamai Certificate Provisioning Service",
  "ShortName": "Akamai",
  "Capability": "Akamai",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": false,
    "Create": false,
    "Discovery": false,
    "Enrollment": true,
    "Remove": false
  },
  "Properties": [
    {
      "Name": "access_token",
      "DisplayName": "Access Token",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": false,
      "Description": "The Akamai access_token for authentication."
    },
    {
      "Name": "client_token",
      "DisplayName": "Client Token",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": false,
      "Description": "The Akamai client_token for authentication."
    },
    {
      "Name": "client_secret",
      "DisplayName": "Client Secret",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": false,
      "Description": "The Akamai client_secret for authentication."
    }
  ],
  "EntryParameters": [
    {
      "Name": "EnrollmentId",
      "DisplayName": "Enrollment ID",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "Description": "Enrollment ID of a certificate enrollment in Akamai. This should only be supplied for ODKG when replacing an existing certificate."
    },
    {
      "Name": "ContractId",
      "DisplayName": "Contract ID",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "The Contract ID of your account in Akamai."
    },
    {
      "Name": "Sans",
      "DisplayName": "SANs",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "Description": "SANs for the new certificate. If multiple are supplied, they should be split with an ampersand character '&'"
    },
    {
      "Name": "admin-addressLineOne",
      "DisplayName": "Admin - Address Line 1",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-addressLineTwo",
      "DisplayName": "Admin - Address Line 2",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "Description": "Optional field for Administrator contact."
    },
    {
      "Name": "admin-city",
      "DisplayName": "Admin - City",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-country",
      "DisplayName": "Admin - Country",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-email",
      "DisplayName": "Admin - Email",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-firstName",
      "DisplayName": "Admin - First Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-lastName",
      "DisplayName": "Admin - Last Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-organizationName",
      "DisplayName": "Admin - Organization Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-phone",
      "DisplayName": "Admin - Phone",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-postalCode",
      "DisplayName": "Admin - Postal Code",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-region",
      "DisplayName": "Admin - Region",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-title",
      "DisplayName": "Admin - Title",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "org-addressLineOne",
      "DisplayName": "Org - Address Line 1",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Organization contact."
    },
    {
      "Name": "org-addressLineTwo",
      "DisplayName": "Org - Address Line 2",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "Description": "Optional field for Organization contact."
    },
    {
      "Name": "org-city",
      "DisplayName": "Org - City",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Organization contact."
    },
    {
      "Name": "org-country",
      "DisplayName": "Org - Country",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Organization contact."
    },
    {
      "Name": "org-organizationName",
      "DisplayName": "Org - Organization Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Organization contact."
    },
    {
      "Name": "org-phone",
      "DisplayName": "Org - Phone",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Organization contact."
    },
    {
      "Name": "org-postalCode",
      "DisplayName": "Org - Postal Code",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Organization contact."
    },
    {
      "Name": "org-region",
      "DisplayName": "Org - Region",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Organization contact."
    },
    {
      "Name": "tech-addressLineOne",
      "DisplayName": "Tech - Address Line 1",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "tech-addressLineTwo",
      "DisplayName": "Tech - Address Line 2",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "Description": "Optional field for Akamai Tech contact."
    },
    {
      "Name": "tech-city",
      "DisplayName": "Tech - City",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "tech-country",
      "DisplayName": "Tech - Country",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "tech-email",
      "DisplayName": "Tech - Email",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact. Must be an akamai.com email address."
    },
    {
      "Name": "tech-firstName",
      "DisplayName": "Tech - First Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "tech-lastName",
      "DisplayName": "Tech - Last Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "tech-organizationName",
      "DisplayName": "Tech - Organization Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "Akamai",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "tech-phone",
      "DisplayName": "Tech - Phone",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "tech-postalCode",
      "DisplayName": "Tech - Postal Code",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "tech-region",
      "DisplayName": "Tech - Region",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "tech-title",
      "DisplayName": "Tech - Title",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "deployment-network",
      "DisplayName": "Deployment Network",
      "Type": "MultipleChoice",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "Options": "Standard TLS,Enhanced TLS",
      "DefaultValue": "Standard TLS",
      "Description": "Required field for Deployment Network."
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathType": "MultipleChoice",
  "StorePathValue": "[\"Production\",\"Staging\"]",
  "PrivateKeyAllowed": "Forbidden",
  "ServerRequired": false,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Forbidden"
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

