#!/usr/bin/env bash

# Creates all 1 store types via the Keyfactor Command REST API using curl.
#
# Authentication (first matching method is used):
#   OAuth access token:   KEYFACTOR_AUTH_ACCESS_TOKEN
#   OAuth client creds:   KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET
#                         + KEYFACTOR_AUTH_TOKEN_URL
#   Basic auth (AD):      KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN
#
# Always required:
#   KEYFACTOR_HOSTNAME    Command hostname (e.g. my-command.example.com)
#
# Auto-generated by doctool generate-store-type-scripts — do not edit by hand.

if [ -z "${KEYFACTOR_HOSTNAME}" ]; then
    echo "ERROR: KEYFACTOR_HOSTNAME is required"
    exit 1
fi

BASE_URL="https://${KEYFACTOR_HOSTNAME}/keyfactorapi"

# ---------------------------------------------------------------------------
# Resolve auth
# ---------------------------------------------------------------------------
if [ -n "${KEYFACTOR_AUTH_ACCESS_TOKEN}" ]; then
    BEARER_TOKEN="${KEYFACTOR_AUTH_ACCESS_TOKEN}"
elif [ -n "${KEYFACTOR_AUTH_CLIENT_ID}" ] && [ -n "${KEYFACTOR_AUTH_CLIENT_SECRET}" ] && [ -n "${KEYFACTOR_AUTH_TOKEN_URL}" ]; then
    echo "Fetching OAuth token..."
    BEARER_TOKEN=$(curl -s -X POST "${KEYFACTOR_AUTH_TOKEN_URL}" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        --data-urlencode "grant_type=client_credentials" \
        --data-urlencode "client_id=${KEYFACTOR_AUTH_CLIENT_ID}" \
        --data-urlencode "client_secret=${KEYFACTOR_AUTH_CLIENT_SECRET}" | jq -r '.access_token')
    if [ -z "${BEARER_TOKEN}" ] || [ "${BEARER_TOKEN}" = "null" ]; then
        echo "ERROR: Failed to fetch OAuth token from ${KEYFACTOR_AUTH_TOKEN_URL}"
        exit 1
    fi
elif [ -n "${KEYFACTOR_USERNAME}" ] && [ -n "${KEYFACTOR_PASSWORD}" ] && [ -n "${KEYFACTOR_DOMAIN}" ]; then
    BEARER_TOKEN=""
else
    echo "ERROR: Authentication required. Set one of:"
    echo "  KEYFACTOR_AUTH_ACCESS_TOKEN"
    echo "  KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET + KEYFACTOR_AUTH_TOKEN_URL"
    echo "  KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN"
    exit 1
fi

if [ -n "${BEARER_TOKEN}" ]; then
    CURL_AUTH=("-H" "Authorization: Bearer ${BEARER_TOKEN}")
else
    CURL_AUTH=("-u" "${KEYFACTOR_USERNAME}@${KEYFACTOR_DOMAIN}:${KEYFACTOR_PASSWORD}")
fi

create_store_type() {
    local name="$1"
    local body="$2"
    echo "Creating ${name} store type..."
    response=$(curl -s -o /dev/null -w "%{http_code}" \
        -X POST "${BASE_URL}/certificatestoretypes" \
        -H "Content-Type: application/json" \
        -H "x-keyfactor-requested-with: APIClient" \
        "${CURL_AUTH[@]}" \
        -d "${body}")
    if [ "$response" = "200" ] || [ "$response" = "201" ]; then
        echo "  OK (HTTP ${response})"
    else
        echo "  FAILED (HTTP ${response})"
    fi
}

# ---------------------------------------------------------------------------
# Akamai — The Client Machine field is the Akamai REST API URL. This should be equal to the "host" value from the API credentials file.
# ---------------------------------------------------------------------------
create_store_type "Akamai" '{
  "Name": "Akamai Certificate Provisioning Service",
  "ShortName": "Akamai",
  "Capability": "Akamai",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": false,
    "Create": false,
    "Discovery": false,
    "Enrollment": true,
    "Remove": false
  },
  "Properties": [
    {
      "Name": "access_token",
      "DisplayName": "Access Token",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": false
    },
    {
      "Name": "client_token",
      "DisplayName": "Client Token",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": false
    },
    {
      "Name": "client_secret",
      "DisplayName": "Client Secret",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": false
    }
  ],
  "EntryParameters": [
    {
      "Name": "EnrollmentId",
      "DisplayName": "Enrollment ID",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "Description": "Enrollment ID of a certificate enrollment in Akamai. This should only be supplied for ODKG when replacing an existing certificate."
    },
    {
      "Name": "ContractId",
      "DisplayName": "Contract ID",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "The Contract ID of your account in Akamai."
    },
    {
      "Name": "Sans",
      "DisplayName": "SANs",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "Description": "SANs for the new certificate. If multiple are supplied, they should be split with an ampersand character '&'"
    },
    {
      "Name": "admin-addressLineOne",
      "DisplayName": "Admin - Address Line 1",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-addressLineTwo",
      "DisplayName": "Admin - Address Line 2",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "Description": "Optional field for Administrator contact."
    },
    {
      "Name": "admin-city",
      "DisplayName": "Admin - City",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-country",
      "DisplayName": "Admin - Country",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-email",
      "DisplayName": "Admin - Email",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-firstName",
      "DisplayName": "Admin - First Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-lastName",
      "DisplayName": "Admin - Last Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-organizationName",
      "DisplayName": "Admin - Organization Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-phone",
      "DisplayName": "Admin - Phone",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-postalCode",
      "DisplayName": "Admin - Postal Code",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-region",
      "DisplayName": "Admin - Region",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "admin-title",
      "DisplayName": "Admin - Title",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Administrator contact."
    },
    {
      "Name": "org-addressLineOne",
      "DisplayName": "Org - Address Line 1",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Organization contact."
    },
    {
      "Name": "org-addressLineTwo",
      "DisplayName": "Org - Address Line 2",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "Description": "Optional field for Organization contact."
    },
    {
      "Name": "org-city",
      "DisplayName": "Org - City",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Organization contact."
    },
    {
      "Name": "org-country",
      "DisplayName": "Org - Country",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Organization contact."
    },
    {
      "Name": "org-organizationName",
      "DisplayName": "Org - Organization Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Organization contact."
    },
    {
      "Name": "org-phone",
      "DisplayName": "Org - Phone",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Organization contact."
    },
    {
      "Name": "org-postalCode",
      "DisplayName": "Org - Postal Code",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Organization contact."
    },
    {
      "Name": "org-region",
      "DisplayName": "Org - Region",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Organization contact."
    },
    {
      "Name": "tech-addressLineOne",
      "DisplayName": "Tech - Address Line 1",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "tech-addressLineTwo",
      "DisplayName": "Tech - Address Line 2",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "Description": "Optional field for Akamai Tech contact."
    },
    {
      "Name": "tech-city",
      "DisplayName": "Tech - City",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "tech-country",
      "DisplayName": "Tech - Country",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "tech-email",
      "DisplayName": "Tech - Email",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact. Must be an akamai.com email address."
    },
    {
      "Name": "tech-firstName",
      "DisplayName": "Tech - First Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "tech-lastName",
      "DisplayName": "Tech - Last Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "tech-organizationName",
      "DisplayName": "Tech - Organization Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "Akamai",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "tech-phone",
      "DisplayName": "Tech - Phone",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "tech-postalCode",
      "DisplayName": "Tech - Postal Code",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "tech-region",
      "DisplayName": "Tech - Region",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "tech-title",
      "DisplayName": "Tech - Title",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "DefaultValue": "SET-DEFAULT",
      "Description": "Required field for Akamai Tech contact."
    },
    {
      "Name": "deployment-network",
      "DisplayName": "Deployment Network",
      "Type": "MultipleChoice",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "Options": "Standard TLS,Enhanced TLS",
      "DefaultValue": "Standard TLS",
      "Description": "Required field for Deployment Network."
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathType": "MultipleChoice",
  "StorePathValue": "[\"Production\",\"Staging\"]",
  "PrivateKeyAllowed": "Forbidden",
  "ServerRequired": false,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Forbidden",
  "StorePathDescription": "The Akamai network the certificate will be managed from. Value can be either \"Production\" or \"Staging\"."
}'


echo "Completed."
